name: Release
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_SDK_VERSION: 5.0.x

on:
  push:
    tags:
      - 'v*'

jobs:
  Release:
    name: Release
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

    - name: Cleanup
      run: dotnet clean --configuration Release && dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Publish solution
      shell: bash
      run: |
        dotnet publish --configuration Release --no-build --no-restore -o artifacts
        7z a -tzip "FileResaver.zip" ".\artifacts\*"

    - name: Create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        #body_path: CHANGELOG.md

    - name: Upload release asset
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: FileResaver.zip
        asset_name: FileResaver-${{ github.ref }}.zip
        asset_content_type: application/zip
