name: Release
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_SDK_VERSION: 5.0.x

on:
  push:
    tags:
      - 'v*'

jobs:
  Release:
    name: Release
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

    - name: Cleanup
      run: dotnet clean --configuration Release && dotnet nuget locals all --clear

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Create release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
